language: objective-c
install:
  - wget "https://developers.facebook.com/resources/facebook-ios-sdk-current.pkg"
  - sudo installer -pkg "facebook-ios-sdk-current.pkg" -target /

branches:
  only:
      - /^.*$/

before_script:
  - killall -9 "iOS Simulator"
  
script: xcodebuild test -project mvt-ios.xcodeproj -scheme mvt-iosTests
