language: objective-c

install:
  - chmod +x configure.sh
  - sh configure.sh
branches:
  only:
      - /^.*$/

script: xcodebuild test -project mvt-ios.xcodeproj -scheme mvt-iosTests -destination 'platform=iOS Simulator,name=iPhone 5s'
