language: objective-c

install:
  - wget "https://developers.facebook.com/resources/facebook-ios-sdk-current.pkg"
  - sudo installer -pkg "facebook-ios-sdk-current.pkg" -target /
  - wget "http://developers.google.com/+/mobile/ios/sdk/google-plus-ios-sdk-1.7.1.zip"
  - sudo cp google-plus-ios-sdk-1.7.1.zip /Documents
  - sudo unzip /Documents/google-plus-ios-sdk-1.7.1.zip /Documents

branches:
  only:
      - /^.*$/

script: xcodebuild test -project mvt-ios.xcodeproj -scheme mvt-iosTests -destination 'platform=iOS Simulator,name=iPhone 5s'
